default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: go_now_development
  username: postgres
  password: postgresql_123

test:
  <<: *default
  host: localhost
  database: go_now_test
  username: postgres
  password: postgresql_123

# production:
#  <<: *default
#  database: go_now_production
#  username: go_now
#  password: <%= ENV['GO_NOW_DATABASE_PASSWORD'] %>
